let one = parseInt(prompt('Enter first digit'))
let two = parseInt(prompt('Enter second digit'))
let three = parseInt(prompt('third digit'))
let four = parseInt(prompt('fourth digit'))
let five = parseInt(prompt('fifth digit'))
console.log('Addition sum: ' + Math.round(one + two + three + four + five))
console.log('Product: ' + Math.round(one * two * three * four * five))
console.log('Max: ' + Math.max(one, two, three, four, five))
console.log('Min: ' + Math.min(one, two, three, four, five))
